# A generic, single database configuration.

[alembic]
# path to migration scripts.
script_location = %(here)s/alembic

[alembic:database]
# Указываем URL вашей базы данных SQLite
sqlalchemy.url = sqlite:///shop.db

# sys.path path, будет добавлен в sys.path
prepend_sys_path = .

# path separator для версий
path_separator = os

[post_write_hooks]
# hooks можно настроить здесь, если требуется (black, ruff и т.д.)

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S