"""Add hashed_password to users

Revision ID: 6233fa52f4ee
Revises: 74b5b3ac4c05
Create Date: 2026-03-26 04:11:03.596991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6233fa52f4ee'
down_revision: Union[str, Sequence[str], None] = '74b5b3ac4c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
